#ifndef STUDENTS_DATA_APPLICATION_BINARYSEARCHTREE_H
#define STUDENTS_DATA_APPLICATION_BINARYSEARCHTREE_H

template<class T>
class BinarySearchTree {

};


#endif //STUDENTS_DATA_APPLICATION_BINARYSEARCHTREE_H
